
package com.hael.wsClient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-27T15:21:38.048-04:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "IOException", targetNamespace = "http://evetool.hael.com/")
public class IOException_Exception extends Exception {
    
    private com.hael.wsClient.IOException ioException;

    public IOException_Exception() {
        super();
    }
    
    public IOException_Exception(String message) {
        super(message);
    }
    
    public IOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, com.hael.wsClient.IOException ioException) {
        super(message);
        this.ioException = ioException;
    }

    public IOException_Exception(String message, com.hael.wsClient.IOException ioException, Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

    public com.hael.wsClient.IOException getFaultInfo() {
        return this.ioException;
    }
}
