
package com.hael.wsClient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-27T15:21:38.034-04:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "NoPathExistsException", targetNamespace = "http://evetool.hael.com/")
public class NoPathExistsException_Exception extends Exception {
    
    private com.hael.wsClient.NoPathExistsException noPathExistsException;

    public NoPathExistsException_Exception() {
        super();
    }
    
    public NoPathExistsException_Exception(String message) {
        super(message);
    }
    
    public NoPathExistsException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NoPathExistsException_Exception(String message, com.hael.wsClient.NoPathExistsException noPathExistsException) {
        super(message);
        this.noPathExistsException = noPathExistsException;
    }

    public NoPathExistsException_Exception(String message, com.hael.wsClient.NoPathExistsException noPathExistsException, Throwable cause) {
        super(message, cause);
        this.noPathExistsException = noPathExistsException;
    }

    public com.hael.wsClient.NoPathExistsException getFaultInfo() {
        return this.noPathExistsException;
    }
}
