
package com.hael.wsClient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-27T15:21:37.926-04:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "NotARealSolarSystem", targetNamespace = "http://evetool.hael.com/")
public class NotARealSolarSystemException extends Exception {
    
    private com.hael.wsClient.NotARealSolarSystem notARealSolarSystem;

    public NotARealSolarSystemException() {
        super();
    }
    
    public NotARealSolarSystemException(String message) {
        super(message);
    }
    
    public NotARealSolarSystemException(String message, Throwable cause) {
        super(message, cause);
    }

    public NotARealSolarSystemException(String message, com.hael.wsClient.NotARealSolarSystem notARealSolarSystem) {
        super(message);
        this.notARealSolarSystem = notARealSolarSystem;
    }

    public NotARealSolarSystemException(String message, com.hael.wsClient.NotARealSolarSystem notARealSolarSystem, Throwable cause) {
        super(message, cause);
        this.notARealSolarSystem = notARealSolarSystem;
    }

    public com.hael.wsClient.NotARealSolarSystem getFaultInfo() {
        return this.notARealSolarSystem;
    }
}
