
package com.hael.wsClient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-11-03T12:11:27.772-04:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "NotEnoughArguments", targetNamespace = "http://evetool.hael.com/")
public class NotEnoughArgumentsException extends Exception {
    
    private com.hael.wsClient.NotEnoughArguments notEnoughArguments;

    public NotEnoughArgumentsException() {
        super();
    }
    
    public NotEnoughArgumentsException(String message) {
        super(message);
    }
    
    public NotEnoughArgumentsException(String message, Throwable cause) {
        super(message, cause);
    }

    public NotEnoughArgumentsException(String message, com.hael.wsClient.NotEnoughArguments notEnoughArguments) {
        super(message);
        this.notEnoughArguments = notEnoughArguments;
    }

    public NotEnoughArgumentsException(String message, com.hael.wsClient.NotEnoughArguments notEnoughArguments, Throwable cause) {
        super(message, cause);
        this.notEnoughArguments = notEnoughArguments;
    }

    public com.hael.wsClient.NotEnoughArguments getFaultInfo() {
        return this.notEnoughArguments;
    }
}
